import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {newJournal, applyJournalCommand, commandFingerprint, grindSummary, isTargetSpecies, exportJournal, importJournal} from '../public/browser-journal.js';
const now='2026-10-01T00:00:00.000Z';
const medals=['unknown','none','bronze','silver','gold','diamond','great_one'];
async function command(doc,op,data){const c={id:randomUUID(),op,expectedRevision:doc.revision,data};return applyJournalCommand(doc,c,await commandFingerprint(c),now).journal;}
async function fixture(rows=[]){let doc=newJournal({journalId:randomUUID(),platform:'xbox',now});doc=await command(doc,'grind.start',{grindId:randomUUID(),name:'Phone grind',targetSpecies:'Whitetail Deer',reserve:19});for(const row of rows)doc=await command(doc,'report.add',{reportId:randomUUID(),grindId:doc.grinds[0].id,version:1,species:'Whitetail Deer',score:null,medal:'unknown',sex:'unknown',occurredAt:now,placeId:null,points:{},notes:'',...row});return doc;}
const summary=doc=>grindSummary(doc,doc.grinds[0].id);
test('all seven explicit medal categories exist even on an empty grind',async()=>{const s=summary(await fixture());for(const scope of ['target','other','all'])assert.deepEqual(s.medalCounts[scope],Object.fromEntries(medals.map(m=>[m,0])));assert.equal(grindSummary({grinds:[],reports:[]},randomUUID()),null);});
test('case and outer whitespace match without merging aliases or internal spaces',()=>{assert(isTargetSpecies(' whitetail deer ','Whitetail Deer'));assert(isTargetSpecies('Whitetail Deer',' WHITETAIL DEER '));for(const species of ['Whitetail','White-tailed Deer','Whitetail  Deer'])assert.equal(isTargetSpecies(species,'Whitetail Deer'),false);});
test('mixed medal counts partition target and other while retaining explicit unknown',async()=>{const rows=medals.flatMap(medal=>[{species:' whitetail deer ',medal,score:medal==='unknown'?999999:null},{species:'Moose',medal}]);rows.push({species:'Whitetail',medal:'diamond'},{species:'Whitetail  Deer',medal:'gold'});const doc=await fixture(rows),before=structuredClone(doc),s=summary(doc);assert.deepEqual([s.target,s.other,s.total,s.diamonds,s.greatOnes],[7,9,16,1,1]);for(const medal of medals){assert.equal(s.medalCounts.target[medal],1);assert.equal(s.medalCounts.all[medal],s.medalCounts.target[medal]+s.medalCounts.other[medal]);}for(const scope of ['target','other','all'])assert.equal(Object.values(s.medalCounts[scope]).reduce((a,b)=>a+b,0),scope==='all'?s.total:s[scope]);assert.equal(s.medalCounts.target.unknown,1);assert.equal(s.medalCounts.target.none,1);assert.deepEqual(doc,before);});
test('target gold plus other diamond preserves the target headline and scoped counts',async()=>{const s=summary(await fixture([{medal:'gold'},{species:'Moose',medal:'diamond'}]));assert.equal(s.diamonds,0);assert.equal(s.medalCounts.target.gold,1);assert.equal(s.medalCounts.other.diamond,1);assert.equal(s.medalCounts.all.diamond,1);});
test('high score without a recorded medal never becomes a diamond',async()=>{const s=summary(await fixture([{score:999999}]));assert.equal(s.diamonds,0);assert.equal(s.medalCounts.all.diamond,0);assert.equal(s.medalCounts.all.unknown,1);assert.equal(s.medalCounts.all.none,0);});
test('import export retains raw authored labels and evidence with identical derived counts',async()=>{const doc=await fixture([{species:' whitetail deer ',medal:'silver',notes:'Raw note',points:{shot:{x:0,z:25}}},{species:'Whitetail',medal:'none'}]);doc.reports[0].species=' whitetail deer ';doc.grinds[0].targetSpecies=' Whitetail Deer ';const restored=importJournal(exportJournal(doc));assert.deepEqual(restored,doc);assert.equal(restored.reports[0].species,' whitetail deer ');assert.deepEqual(summary(restored),summary(doc));});
